---
title: "Trabajo1_R"
author: "Rodrigo Reyes"
date: "2023-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(grid)

```

```{r}
Trabajo_personal_R <- read_excel("Trabajo personal R.xlsx")

ggplot(Trabajo_personal_R, aes(MO))+
geom_histogram(color="black", fill="red", bins = 10)+
labs(title="Histograma Mortalidad (%)", x="Mortalidad (%)",
y="Frecuencia") + theme_gray()

```
```{r}

ggplot(Trabajo_personal_R, aes(SFR))+
geom_histogram(color="black", fill="green", bins = 10)+
labs(title="Histograma SFR (%)", x="SFR (%)",
y="Frecuencia") + theme_gray()

```

```{r}

ggplot(Trabajo_personal_R, aes(x=DIETA, y=MO))+
geom_boxplot(color="black", fill="red", bins = 10)+
labs(title="Boxplot Mortalidad (%)", x="DIETA", y="Mortalidad") + theme_gray()

```
```{r}
ggplot(Trabajo_personal_R, aes(x=DIETA, y=SFR))+
geom_boxplot(color="black", fill="green", bins = 10)+
labs(title="Boxplot SFR (%)", x="DIETA", y="SFR") + theme_gray()

```
```{r}

str(Trabajo_personal_R)

```
```{r}

summary(Trabajo_personal_R)
```
```{r}

dim(Trabajo_personal_R)

```
```{r}

Trabajo_personal_R_new <- na.omit(Trabajo_personal_R)

```

```{r}

dim(Trabajo_personal_R_new)

```
```{r}

ggplot(Trabajo_personal_R, aes(x=Fecha, y=MO))+
geom_line(color="red", bins = 10)+
labs(title="Linea Mortalidad (%)", x="Fecha", y="Mortalidad") + theme_gray()
```
```{r}
ggplot(Trabajo_personal_R, aes(x=Fecha, y=SFR))+
geom_line(color="green", bins = 10)+
labs(title="Linea SFR (%)", x="Fecha", y="SFR") + theme_gray()
```
```{r}

